"""Generated by scripts/gen_tools.py from the Glasser OpenAPI document. Do not edit.

Which fields of each capability the API takes as arrays (the plugin splits a
comma-separated string) and as integers (the plugin coerces the number).
"""

SOLUTION = 'gtm'

CAPABILITIES = ["company_intelligence", "market_data", "people_search", "seo_research", "social_research", "web_research"]

LIST_FIELDS = {
    'company_intelligence': [],
    'market_data': [],
    'people_search': ["job_titles", "locations", "seniorities"],
    'seo_research': ["keywords"],
    'social_research': [],
    'web_research': [],
}

INT_FIELDS = {
    'company_intelligence': [],
    'market_data': [],
    'people_search': [],
    'seo_research': [],
    'social_research': [],
    'web_research': [],
}
